"""add roles default

Revision ID: 04d4dd38a7f6
Revises: 1a7c141d4d7b
Create Date: 2024-07-05 10:58:07.402409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d4dd38a7f6'
down_revision: Union[str, None] = '1a7c141d4d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
