"""add roles

Revision ID: 1a7c141d4d7b
Revises: 92a097454745
Create Date: 2024-07-05 10:57:36.345663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7c141d4d7b'
down_revision: Union[str, None] = '92a097454745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('role', sa.Enum('ADMIN', 'USER', name='roles'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'role')
    # ### end Alembic commands ###
