"""init user

Revision ID: 38013a5b0bb0
Revises: 
Create Date: 2024-07-04 21:24:58.470642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38013a5b0bb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('student_number', sa.String(), nullable=True),
    sa.Column('ipk', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('student_number ~ \'^[0-9]+$\'', name='student_number_check'),
    sa.CheckConstraint('ipk >= 0 AND ipk <= 4', name='ipk_range_check'),
    sa.CheckConstraint("phone_number ~ '^\+?[0-9]+$'", name='phone_number_check')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
