"""add soft delete division

Revision ID: 652cd6b7f18c
Revises: bc81fe833a88
Create Date: 2024-07-31 19:32:56.327602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652cd6b7f18c'
down_revision: Union[str, None] = 'bc81fe833a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intern_division', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intern_division', 'is_deleted')
    # ### end Alembic commands ###
