"""set new model

Revision ID: a25b05c04592
Revises: 87fc646654e0
Create Date: 2024-07-14 18:37:59.376105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25b05c04592'
down_revision: Union[str, None] = '87fc646654e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intern_registration', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intern_registration', 'duration')
    # ### end Alembic commands ###
