"""add model validation

Revision ID: f4f071d64a83
Revises: 32fad41a5c99
Create Date: 2024-07-05 15:07:08.099043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f071d64a83'
down_revision: Union[str, None] = '32fad41a5c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intern_division', 'division_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'intern_division', ['division_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intern_division', type_='unique')
    op.alter_column('intern_division', 'division_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
